version: 2
jobs:
  build:
    working_directory: ~/czhx-web
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Init Yarn
          command: 'yarn'
          path: ~/czhx-web
      - run:
          name: Unit Test
          command: 'yarn test'
          path: ~/czhx-web
      - run:
          name: Build
          command: 'yarn build'
          path: ~/czhx-web
      - store_artifacts:
          path: build
