version: 2
jobs:
  build:
    working_directory: ~/czhx-web
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: init yarn
          command: 'yarn'
      - run:
          name: unit test
          command: 'yarn test'
      - run:
          name: build potentially shippable product
          command: 'yarn build'
      - store_artifacts:
          path: build
